kind: Service
apiVersion: v1
metadata:
  name: netcoreapi-svc
spec:
  selector:
    app: netcoreapi
  ports:
  - protocol: "TCP"
    port: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcoreapi
  labels:
    app: netcoreapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netcoreapi
  template:
    metadata:
      labels:
        app: netcoreapi
    spec:
      containers:
      - name: netcoreapi
        image: netcoreapi
        imagePullPolicy: Never